name: Build Engineering Calculator Pro ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check project files
        run: |
          pwd
          ls -la
          echo "===== PUBSPEC ====="
          cat pubspec.yaml
          echo "===== MAIN DART ====="
          ls -lh lib/main.dart
          echo "===== CHECK COMPLETE ====="
      

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Pub Get
        run: 
          echo "Checking Flutter project..."
          ls -la
          echo "Checking pubspec.yaml..."
          cat pubspec.yaml
      - name: Flutter Analyze
        run: flutter analyze

      - name: Build ARM64 APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Engineering-Calculator-Pro-ARM64
          path: build/app/outputs/flutter-apk/app-release.apk
