name: Build Engineering Calculator Pro ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check Project
        run: |
          echo "===== PROJECT ROOT ====="
          pwd
          echo "===== FILES ====="
          ls -la
          echo "===== PUBSPEC ====="
          cat pubspec.yaml
          echo "===== MAIN DART ====="
          ls -lh lib/main.dart

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Generate Android Project
        run: |
          flutter create --platforms=android --project-name engineering_calculator_pro .
          flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Build ARM64 APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Engineering-Calculator-Pro-ARM64
          path: build/app/outputs/flutter-apk/app-release.apk
